name: CI

on:
  push:
    branches: [v1, v2]
  pull_request:
    branches: [v1, v2]

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: rundocs/checkout@master
