name: CI

on:
  push:
    branches: [ master, debug ]
  pull_request:
    branches: [ master, debug ]

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: rundocs/checkout@master
