name: debug

on:
  push:
    branches: [ debug ]
  pull_request:
    branches: [ debug ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        git clone --depth=1 "https://${GITHUB_ACTOR}:${{ secrets.DEBUG_AUTH_TOKEN }}@github.com/rundocs/debug.git" .debug
        rm -rf .debug/* && cp -rf * .debug && cd .debug
        git add .
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git commit -m "${GITHUB_SHA}" && git push
